#!/bin/sh
#
# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
# sbang project developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# `sbang`: Run scripts with long shebang lines.
#
# Many operating systems limit the length and number of possible
# arguments in shebang lines, making it hard to use interpreters that are
# deep in the directory hierarchy or require special arguments.
#
# To use, put the long shebang on the second line of your script, and
# make sbang the interpreter, like this:
#
#     #!/bin/sh /path/to/sbang
#     #!/long/path/to/real/interpreter with arguments
#
# `sbang` will run the real interpreter with the script as its argument.
#
# See https://github.com/spack/sbang for more details.
#
# If using python source code encoding, put that on the second line of the file
# and the shebang line for the long path to the real interpreter on the third
# line, like this:
#
#     #!/bin/sh /path/to/sbang
#     # -*- coding: utf-8 -*-
#     #!/long/path/to/real/interpreter with arguments
#

# Generic error handling
die() {
    echo "$@" 1>&2;
    exit 1
}

# set SBANG_DEBUG to make the script print what would normally be executed.
exec="exec"
if [ -n "${SBANG_DEBUG}" ]; then
    exec="echo "
fi

# First argument is the script we want to actually run.
script="$1"

# ensure that the script actually exists
if [ -z "$script" ]; then
    die "error: sbang requires exactly one argument"
elif [ ! -f "$script" ]; then
    die "$script: no such file or directory"
fi

# Search the first two lines of script for interpreters.
# Search the third line if one of the first two is an encoding declaration
lines=0
while read -r line && [ $lines -ne 2 ]; do
    if [ "${line#\#!}" != "$line" ]; then
        shebang_line="${line#\#!}"
    elif [ "${line#//!}" != "$line" ]; then      # // comments
        shebang_line="${line#//!}"
    elif [ "${line#--!}" != "$line" ]; then      # -- lua comments
        shebang_line="${line#--!}"
    elif [ "${line#<?php\ }" != "$line" ]; then  # php comments
        shebang_line="${line#<?php\ \#!}"
        shebang_line="${shebang_line%\ ?>}"
    else
        # Check whether this is a python/ruby encoding line
        # Strip leading whitespace, whitespace is allowed before encoding
        leading_whitespace=${line%%[![:space:]]*}
        line=${line#"$leading_whitespace"}
        # python/ruby encoding lines must start with comment character
        if [ "${line#\#}" != "$line" ]; then
            # If coding: or coding= in the line, it matches pep263
            case "$line" in
                *"coding:"* | *"coding="*)
                    sbang_skip_encoding_line=1
                    ;;
                *)
                    ;;
            esac
        fi
    fi
    # Don't count the line as part of the two to search if it's an encoding
    if [ "${sbang_skip_encoding_line}" = "1" ]; then
        unset sbang_skip_encoding_line
    else
        lines=$((lines+1))
    fi
done < "$script"

# error if we did not find any interpreter
if [ -z "$shebang_line"  ]; then
    die "error: sbang found no interpreter in $script"
fi

# parse out the interpreter and first argument
IFS=' ' read -r interpreter arg1 rest <<EOF
$shebang_line
EOF

# Determine if the interpreter is a particular program, accounting for the
# '#!/usr/bin/env PROGRAM' convention. So:
#
#     interpreter_is perl
#
# will be true for '#!/usr/bin/perl' and '#!/usr/bin/env perl'
interpreter_is() {
    case "${interpreter##*/}" in
        "$1"*) return 0 ;;
    esac

    if [ "$interpreter" = "/usr/bin/env" ]; then
        case "$arg1" in
            "$1"*) return 0 ;;
        esac
    fi

    return 1
}

if interpreter_is "sbang"; then
    die "error: refusing to re-execute sbang to avoid infinite loop."
fi

# Finally invoke the real shebang line
# ruby and perl need -x to ignore the first line of input (the sbang line)
#
if interpreter_is perl || interpreter_is ruby; then
    # shellcheck disable=SC2086
    $exec $shebang_line -x "$@"
else
    # shellcheck disable=SC2086
    $exec $shebang_line "$@"
fi
