name: linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup kcov
      run: |
        sudo apt update
        sudo apt install -y binutils-dev build-essential cmake libssl-dev libcurl4-openssl-dev libelf-dev libdw-dev zlib1g-dev libiberty-dev git
        git clone https://github.com/SimonKagstrom/kcov.git
        cd kcov
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install
    - name: run unit tests
      env:
        COVERAGE: true
      run: |
          make -C test test
    - uses: codecov/codecov-action@v1
      with:
        directory: .coverage
        flags: unittests
