name: linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y rustc cargo
        cargo install cargo-make
        cargo make kcov-install-debian
    - name: run unit tests
      env:
        COVERAGE: true
      run: |
          make -C test test
    - uses: codecov/codecov-action@v1
      with:
        directory: .coverage
        flags: unittests
