name: macos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run unit tests
      run: |
        make -C test test
